FORMAT: 1A
HOST: http://itas.apiary.io/
VERSION: 1.1

# e-Invoicing Custom API v1.3

## Disclaimer

**** Warning: at this point, ITAS API does not support asynchronous or multithreading calls for POST, PUT, PATCH and DELETE requests. Async or multithreading requests could result in various Error messages, or even a corruption of data in extreme cases and are therefore not supported. ****
<br />
<br />
<strong>Release notes</strong> (6<sup>th</sup> May 2026.)

## New Endpoints

<ul>
<li>None</li>
</ul>

## Updated Endpoints

<ul>
<li>Invoices <b>Incoming Invoice Record List</b>: Additional Array InvoiceVatRecords, remove property DocmanDocumentId, Additional Property on InvoiceRecordLeg - BaseQuantity,<a href="/#reference/invoices/incoming-invoice-record-list/list-incoming-invoice-records"> Link</a></li>
<li>Invoices <b>Incoming Invoice Record Create</b>: Additional Array InvoiceVatRecords, remove property DocmanDocumentId, Additional Property on InvoiceRecordLeg - BaseQuantity,<a href="/#reference/invoices/incoming-invoice-record-create/create-incoming-invoice-record"> Link</a></li>
<li>Invoices <b>Incoming Invoice Record Update</b>: Additional Array InvoiceVatRecords, remove property DocmanDocumentId, Additional Property on InvoiceRecordLeg - BaseQuantity,<a href="/#reference/invoices/incoming-invoice-record-update-delete/update-incoming-invoice-record"> Link</a></li>
</ul>
<div>** ends ** </div>


## AccessToken [/AT]
Model Header containing AccessToken

+ Model 
    + Header

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg


# Group Invoices

## Incoming Invoice Record List [/Invoices/{TradingEntityId}/IncomingInvoice/{Property}/{PropertyValue}]
`GET` Incoming Invoices.

### List Incoming Invoice Records [GET]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|InvoiceRecordId|Invoice Record Id|`number`||||
|AccountCode|Account Code|`string`|10|||
|ClientReference|Client Reference|`string`|255|||
|CurrencyCode|Currency Code|`string`|3|||
|DocumentDate|Document Date|`datetime`||||
|ValueDate|Value Date|`datetime`||||
|Name|Name|`string`|40|||
|VatRegistrationNo|Vat Registration Number|`string`|20|||
|EInvoiceId|e Invoice Id|`string`|50|||
|TotalInvoiceAmount|Total Invoice Amount|`number`||||
|TotalInvoiceLinesExVatAmount|Total Invoice Lines Excluding Vat Amount|`number`||||
|TotalVatAmount|Total Vat Amount|`number`||||
|InvoicePayableAmount|Invoice Payable Amount|`number`||||
|IBAN|IBAN|`string`|255|||
|BIC|BIC|`string`|255|||
|OrderNumber|Order Number|`string`|255|||
|IsProcessed|Is Processed|`boolean`||||
|TaxScheme|Tax Scheme|`string`|5|||
|SchemeId|Scheme Id|`string`|5|||
|DocumentType|Document Type|`string`|10|||
|Notes|Notes|`string`|4000|||
|InvoiceType|InvoiceType|`string`|60|||
|BuyerOrderNo|Buyer Order Number|`string`|50|||
|BuyerSwiftAddress|Buyer SwiftAddress|`string`|60|||
|BuyerVatRegistrationNo|Buyer Vat Registration No|`string`|20|||
|ClientAddress1|Client Address 1|`string`|60|||
|ClientAddress3|Client Address 3|`string`|60|||
|ClientAddress4|Client Address 4|`string`|60|||
|ClientCountryCode|Client Country Code|`string`|3|||
|ClientFiscalRegistrationNo|Client Fiscal Registration No|`string`|18|||
|ClientPaymentTerms|Client Payment Terms|`string`|99|||
|ClientTitle|Client Title|`string`|200|||
|ClientVatRegistrationNo|Client Vat Registration No|`string`|20|||
|ClientZipCode|Client Zip Code|`string`|40|||
|DeliveryClientAddress1|Delivery Client Address 1|`string`|60|||
|DeliveryClientAddress3|Delivery Client Address 3|`string`|60|||
|DeliveryClientAddress4|Delivery Client Address 4|`string`|60|||
|DeliveryClientCountryCode|Delivery Client Country Code|`string`|3|||
|DeliveryClientTitle|Delivery Client Title|`string`|200|||
|DeliveryClientZipCode|Delivery Client Zip Code|`string`|40|||
|DeliveryDate|Delivery Date|`date`||||
|PaymentMethod|Payment Method|`string`|50|||
|PaymentModeDescription|Payment Mode Description|`string`|50|||
|SupplierAddress3|Supplier Address 3|`string`|60|||
|SupplierAddress4|Supplier Address 4|`string`|60|||
|SupplierCountryCode|Supplier Country Code|`string`|3|||
|SupplierFiscalRegistrationNo|Supplier Fiscal Registration No|`string`|18|||
|SupplierSwiftAddress|Supplier Swift Address|`string`|50|||
|SupplierTitle|Supplier Title|`string`|200|||
|SupplierZipCode|Supplier Zip Code|`string`|40|||
|InvoiceRecordLegs|see <b><a href="/#reference/data-object-definitions/invoice-leg/invoice-leg">Invoice Legs</a></b> object|[array] of `object`||||
|InvoiceVatRecords|see <b><a href="/#reference/data-object-definitions/invoice-vat-record/invoicevatrecord">Invoice Vat Record</a></b> object|[array] of `object`|||Required|


+ Request
    [AccessToken][]
    
+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.
    + Property (optional, enum[string]) ... identify property name to filter by 
       + Members
            + AccountCode
            + ClientReference
            + DocumentDate
            + InvoiceRecordId
            + IsProcessed
    + PropertyValue (optional, string, `ABCDEF.P`) 

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data (array [InvoiceReadBody])
        + Pagination (Pagination)
        + Response (200 SuccessResponse)
    
+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 BadPropertyResponse)
  
+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)

## Incoming Invoice Record Create [/Invoices/{TradingEntityId}/IncomingInvoice]

### Create Incoming Invoice Record [POST]
`POST` Create Incoming Invoice Record in the Staging Table. * <a href="/#introduction/disclaimer"> (Disclaimer)</a>

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|AccountCode|Account Code|`string`|10||Required|
|ClientReference|Client Reference|`string`|255||Required|
|CurrencyCode|Currency Code|`string`|3||Required|
|DocumentDate|Document Date|`datetime`|||Required|
|ValueDate|Value Date|`datetime`|||Required|
|Name|Name|`string`|40||Required|
|VatRegistrationNo|Vat Registration Number|`string`|20||Required|
|EInvoiceId|e Invoice Id|`string`|50||Required|
|TotalInvoiceAmount|Total Invoice Amount|`number`|||Required|
|TotalInvoiceLinesExVatAmount|Total Invoice Lines Excluding Vat Amount|`number`|||Required|
|TotalVatAmount|Total Vat Amount|`number`|||Required|
|InvoicePayableAmount|Invoice Payable Amount|`number`|||Required|
|IBAN|IBAN|`string`|255||Required|
|BIC|BIC|`string`|255||Required|
|OrderNumber|Order Number|`string`|255|||
|TaxScheme|Tax Scheme|`string`|5|||
|SchemeId|Scheme Id|`string`|5|||
|DocumentType|Document Type|`string`|10|||
|Notes|Notes|`string`|4000|||
|InvoiceType|InvoiceType|`string`|60|||
|BuyerOrderNo|Buyer Order Number|`string`|50|||
|BuyerSwiftAddress|Buyer SwiftAddress|`string`|60|||
|BuyerVatRegistrationNo|Buyer Vat Registration No|`string`|20|||
|ClientAddress1|Client Address 1|`string`|60|||
|ClientAddress3|Client Address 3|`string`|60|||
|ClientAddress4|Client Address 4|`string`|60|||
|ClientCountryCode|Client Country Code|`string`|3|||
|ClientFiscalRegistrationNo|Client Fiscal Registration No|`string`|18|||
|ClientPaymentTerms|Client Payment Terms|`string`|99|||
|ClientTitle|Client Title|`string`|200|||
|ClientVatRegistrationNo|Client Vat Registration No|`string`|20|||
|ClientZipCode|Client Zip Code|`string`|40|||
|DeliveryClientAddress1|Delivery Client Address 1|`string`|60|||
|DeliveryClientAddress3|Delivery Client Address 3|`string`|60|||
|DeliveryClientAddress4|Delivery Client Address 4|`string`|60|||
|DeliveryClientCountryCode|Delivery Client Country Code|`string`|3|||
|DeliveryClientTitle|Delivery Client Title|`string`|200|||
|DeliveryClientZipCode|Delivery Client Zip Code|`string`|40|||
|DeliveryDate|Delivery Date|`date`||||
|PaymentMethod|Payment Method|`string`|50|||
|PaymentModeDescription|Payment Mode Description|`string`|50|||
|SupplierAddress3|Supplier Address 3|`string`|60|||
|SupplierAddress4|Supplier Address 4|`string`|60|||
|SupplierCountryCode|Supplier Country Code|`string`|3|||
|SupplierFiscalRegistrationNo|Supplier Fiscal Registration No|`string`|18|||
|SupplierSwiftAddress|Supplier Swift Address|`string`|50|||
|SupplierTitle|Supplier Title|`string`|200|||
|SupplierZipCode|Supplier Zip Code|`string`|40|||
|InvoiceRecordLegs|see <b><a href="/#reference/data-object-definitions/invoice-leg/invoice-leg-for-create">Invoice Leg</a></b> object|[array] of `object`|||Required|
|InvoiceVatRecords|see <b><a href="/#reference/data-object-definitions/invoice-vat-record/invoicevatrecord">Invoice Vat Record</a></b> object|[array] of `object`|||Required|

<hr />

<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|InvoiceRecordId|Invoice Record Id|`number`||||

+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity. 

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (InvoiceCreateBody)

+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data (InvoiceIdResponse)
        + Response (201 CreateResponse)
    
+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)

## Incoming Invoice Record Update & Delete [/Invoices/{TradingEntityId}/IncomingInvoice/{InvoiceRecordId}]

### Update Incoming Invoice Record [PUT]
`PUT` Update Incoming Invoice Record in the Staging Table. * <a href="/#introduction/disclaimer"> (Disclaimer)</a>

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|InvoiceRecordId|Invoice Record Id|`number`|||Required|
|AccountCode|Account Code|`string`|10||Required|
|ClientReference|Client Reference|`string`|255||Required|
|CurrencyCode|Currency Code|`string`|3||Required|
|DocumentDate|Document Date|`datetime`|||Required|
|ValueDate|Value Date|`datetime`|||Required|
|Name|Name|`string`|40||Required|
|VatRegistrationNo|Vat Registration Number|`string`|20||Required|
|EInvoiceId|e Invoice Id|`string`|50||Required|
|TotalInvoiceAmount|Total Invoice Amount|`number`|||Required|
|TotalInvoiceLinesExVatAmount|Total Invoice Lines Excluding Vat Amount|`number`|||Required|
|TotalVatAmount|Total Vat Amount|`number`|||Required|
|InvoicePayableAmount|Invoice Payable Amount|`number`|||Required|
|IBAN|IBAN|`string`|255||Required|
|BIC|BIC|`string`|255||Required|
|OrderNumber|Order Number|`string`|255|||
|IsProcessed|Is Processed|`boolean`||||
|TaxScheme|Tax Scheme|`string`|5|||
|SchemeId|Scheme Id|`string`|5|||
|DocumentType|Document Type|`string`|10|||
|Notes|Notes|`string`|4000|||
|InvoiceType|InvoiceType|`string`|60|||
|BuyerOrderNo|Buyer Order Number|`string`|50|||
|BuyerSwiftAddress|Buyer SwiftAddress|`string`|60|||
|BuyerVatRegistrationNo|Buyer Vat Registration No|`string`|20|||
|ClientAddress1|Client Address 1|`string`|60|||
|ClientAddress3|Client Address 3|`string`|60|||
|ClientAddress4|Client Address 4|`string`|60|||
|ClientCountryCode|Client Country Code|`string`|3|||
|ClientFiscalRegistrationNo|Client Fiscal Registration No|`string`|18|||
|ClientPaymentTerms|Client Payment Terms|`string`|99|||
|ClientTitle|Client Title|`string`|200|||
|ClientVatRegistrationNo|Client Vat Registration No|`string`|20|||
|ClientZipCode|Client Zip Code|`string`|40|||
|DeliveryClientAddress1|Delivery Client Address 1|`string`|60|||
|DeliveryClientAddress3|Delivery Client Address 3|`string`|60|||
|DeliveryClientAddress4|Delivery Client Address 4|`string`|60|||
|DeliveryClientCountryCode|Delivery Client Country Code|`string`|3|||
|DeliveryClientTitle|Delivery Client Title|`string`|200|||
|DeliveryClientZipCode|Delivery Client Zip Code|`string`|40|||
|DeliveryDate|Delivery Date|`date`||||
|PaymentMethod|Payment Method|`string`|50|||
|PaymentModeDescription|Payment Mode Description|`string`|50|||
|SupplierAddress3|Supplier Address 3|`string`|60|||
|SupplierAddress4|Supplier Address 4|`string`|60|||
|SupplierCountryCode|Supplier Country Code|`string`|3|||
|SupplierFiscalRegistrationNo|Supplier Fiscal Registration No|`string`|18|||
|SupplierSwiftAddress|Supplier Swift Address|`string`|50|||
|SupplierTitle|Supplier Title|`string`|200|||
|SupplierZipCode|Supplier Zip Code|`string`|40|||
|InvoiceRecordLegs|see <b><a href="/#reference/data-object-definitions/invoice-leg/invoice-leg">Invoice Leg</a></b> object|[array] of `object`|||Required|
|InvoiceVatRecords|see <b><a href="/#reference/data-object-definitions/invoice-vat-record/invoicevatrecord">Invoice Vat Record</a></b> object|[array] of `object`|||Required|

<hr />

<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|InvoiceRecordId|Invoice Record Id|`number`||||

+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.
    + InvoiceRecordId (required, number, `1`) ... Identity specific invoice record

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (InvoiceUpdateBody)

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data
            + InvoiceRecordId: 1 (number)
        + Response (200 UpdateResponse)
    
+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)


### Delete Incoming Invoice [DELETE]
`DELETE` Incoming Invoice record. * <a href="/#introduction/disclaimer"> (Disclaimer)</a>

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|InvoiceRecordId|Invoice Record Id|`number`|||Required|

<strong>Body Parameters</strong>
<br />
None.


+ Request (application/json)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Body 
    
            {
                none
            }

+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.
    + InvoiceRecordId (required, number, `1`) ... Identity specific invoice record

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data
            + InvoiceRecordId: 1 (number)
        + Response (200 DeletedResponse)
    
+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

+ Response 405 (application/json; charset=utf-8)
    + Attributes (405 Response)

# Group Data Object Definitions
List of re-usable Data Objects referenced as `object` types. Not that these endpoints are not accessable and only here for reference purposes.

## Invoice Record Leg [/InvoiceLeg]
A multipurpose object which can be used by several endpoints and with multiple source tables depending on context. The object described below is generic. 

### InvoiceRecordLeg [GET]
<br /><br />
<strong>Invoice Record Leg object for Create.</strong>

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|Quantity|Quantity|`number`|||Required|
|WeightCode|Weight Code|`string`|4||Required|
|Value|Value|`number`|||Required|
|Price|Price|`number`|||Required|
|VatRatePercentage|Vat Rate Percentage|`number`|||Required|
|InvoiceRecordLegDescription|Invoice Leg Description|`string`|255|||
|VatRateCode|Vat Rate Code|`string`|2|||
|RateTypeCode|Rate Type Code|`string`|1||`A`=Amount, `R`=Rate, `S`=SplitAmount, `W`=WeightRate, `%`=Percent, `Q`=DailyPercent, `C`=PerContainer, `L`=PerRailcar, ` `=None|
|PriceTypeCode|Price Type Code|`string`|1|||
|PaymentModeCode|Payment Mode Code|`string`|1|||
|PaymentId|Payment Id|`string`|255|||
|BuyerOrderIdentifier|Buyer Order Identifier|`string`|50|||
|StartPeriod|Start Period|`datetime`||||
|EndPeriod|End Period|`datetime`||||
|FreeFormatNote|Free Format Note|`string`|255|||
|BaseQuantity|Base Quantity|`number`||||
|ValueType|Value Type|`string`|||`Contract`, `Cost` or `Commission`|
|CostHeadingCode|Cost Heading Code|`string`|8|||
|DocumentReference|Document Reference|`string`|9|||
|InvoiceCurrencyCode|Invoice Currency Code|`string`|3|||
|PhysicalTradeId|Physical Trade Id|`string`|10|||


<br /><br />
<strong>Invoice Record Leg object for Update and Read.</strong>

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|InvoiceRecordId|Invoice Record Id|`number`|||Required|
|InvoiceRecordLegId|Invoice Record Leg Id|`number`||||
|Quantity|Quantity|`number`|||Required|
|WeightCode|Weight Code|`string`|4||Required|
|Value|Value|`number`|||Required|
|Price|Price|`number`|||Required|
|VatRatePercentage|Vat Rate Percentage|`number`|||Required|
|InvoiceRecordLegDescription|Invoice Leg Description|`string`|255|||
|VatRateCode|Vat Rate Code|`string`|2|||
|RateTypeCode|Rate Type Code|`string`|1||`A`=Amount, `R`=Rate, `S`=SplitAmount, `W`=WeightRate, `%`=Percent, `Q`=DailyPercent, `C`=PerContainer, `L`=PerRailcar, ` `=None|
|PriceTypeCode|Price Type Code|`string`|1|||
|PaymentModeCode|Payment Mode Code|`string`|1|||
|PaymentId|Payment Id|`string`|255|||
|BuyerOrderIdentifier|Buyer Order Identifier|`string`|50|||
|StartPeriod|Start Period|`datetime`||||
|EndPeriod|End Period|`datetime`||||
|FreeFormatNote|Free Format Note|`string`|255|||
|BaseQuantity|Base Quantity|`number`||||
|ValueType|Value Type|`string`|||`Contract`, `Cost` or `Commission`|
|CostHeadingCode|Cost Heading Code|`string`|8|||
|DocumentReference|Document Reference|`string`|9|||
|InvoiceCurrencyCode|Invoice Currency Code|`string`|3|||
|PhysicalTradeId|Physical Trade Id|`string`|10|||

+ Response 200 (application/json; charset=utf-8)
+ Attributes (InvoiceUpdateLeg1Create)

## Invoice Vat Record [/InvoiceVatRecord]
A multipurpose object which can be used by several endpoints and with multiple source tables depending on context. The object described below is generic. 

### InvoiceVatRecord [GET]
<br /><br />
<strong>Invoice Record Vat object for Create.</strong>

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ExternalVatCode|External Vat Code|`string`|||Required|
|VatPercentage|Vat Percentage|`number`|||Required|
|VatableAmount|Vatable Amount|`number`|||Required|
|VatAmount|Vat Amount|`number`|||Required|
|ItasVatCode|ITAS Vat Code|`string`|2|||
|ExemptionReasonCode|Exemption Reason Code|`string`|50|||
|ExemptionReasonDescription|Exemption Reason Description|`string`|500|||
|InvoiceAmount|Invoice Amount|`number`||||
|VatCurrencyCode|Vat Currency Code|`string`|3|||


<br /><br />
<strong>Invoice Record Vat object for Update and Read.</strong>

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|InvoiceRecordId|Invoice Record Id|`number`|||Required|
|InvoiceVatRecordId|Invoice Vat Record Id|`number`||||
|ExternalVatCode|External Vat Code|`string`|||Required|
|VatPercentage|Vat Percentage|`number`|||Required|
|VatableAmount|Vatable Amount|`number`|||Required|
|VatAmount|Vat Amount|`number`|||Required|
|ItasVatCode|ITAS Vat Code|`string`|2|||
|ExemptionReasonCode|Exemption Reason Code|`string`|50|||
|ExemptionReasonDescription|Exemption Reason Description|`string`|500|||
|InvoiceAmount|Invoice Amount|`number`||||
|VatCurrencyCode|Vat Currency Code|`string`|3|||

+ Response 200 (application/json; charset=utf-8)
+ Attributes (InvoiceReadVat1)

# Data Structures

## 200 SuccessResponse (object)
+ Value: Success (string)

## 200 UpdateResponse (object)
+ Value: Updated (string)

## 200 DeletedResponse (object)
+ Value: Deleted (string)

## 200 AuthoriseResponse (object)
+ Value: Authorised (string)

## 201 CreateResponse (object)
+ Value: Created (string)

## 201 CreateMessages (object)
+ Messages (array [201 ErrorMessageDetail])

## 201 ErrorMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API5084 - API : {fieldName} has a {fieldName} of {value}.` (string)

## 201 CreateBllMessages (object)
+ Messages (array [201 ErrorBllMessageDetail])

## 201 ErrorBllMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API5084 - API : {fieldName} has a {fieldName} of {value}.` (string)

## 400 Response (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array [400 ErrorMessageDetail])

## 400 ErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5058 - Data : The mandatory field {fieldName} was missing in the request body.` (string)


## 400 BadPropertyResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array[400 BadPropertyErrorMessageDetail])

## 400 BadPropertyErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5074 - API : The value sent in the querystring variable {Property} is not allowed.` (string)


## 400 BadReadResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array[400 BadReadErrorMessageDetail])

## 400 BadReadErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5075 - API : The value sent in the querystring is not allowed.` (string)


## 400 WarningMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API50xx - Data : The field {fieldName} was not found.` (string)

## 400 InfoMessageDetail (object)
+ Severity: Information (string)
+ Message: `API50xx - Data : Now create xyz.` (string)


## 404 Response (object)
+ Response
    + Value: 404 Not Found (string)
+ Messages (array[404 ErrorMessageDetailMessage])

## 404 ErrorMessageDetailMessage (object)
+ Severity: Warning (string)
+ Message: `API5068 - Data : No records found.` (string)


## 405 Response (object)
+ Response
    + Value: 405 Method Not Allowed (string)
+ Messages (array[405 MethodNotAllowedMessage])

## 405 MethodNotAllowedMessage (object)
+ Severity: Error (string)
+ Message: `API5077 - API : That method is not supported, please check the ITAS API documentation.` (string)

## accessToken (object)
+ Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg 

## InvoiceCreateBody (object)
+ AccountCode: `ABCDEFG.P` (required, string)
+ ClientReference: '5879101647' (required, string)
+ CurrencyCode: EUR (required, string)
+ DocumentDate: `2025-07-14T00:00:00Z` (required, string)
+ ValueDate: `2025-08-14T00:00:00Z` (required, string)
+ Name: `Coolblue N.V.` (required, string)
+ VatRegistrationNo: NL823619357Z08 (required, string)
+ EInvoiceId: 0478493179 (required, string)
+ TotalInvoiceAmount: 729.17 (required, number)
+ TotalInvoiceLinesExVatAmount: 745.91 (required, number)
+ TotalVatAmount: 16.74 (required, number)
+ InvoicePayableAmount: 719.27 (required, number)
+ IBAN: UKBMGB22 (required, string)
+ BIC: HBUKGB4B (required, string)
+ OrderNumber: Order 1 (string)
+ TaxScheme: VAT (string)
+ SchemeId: `9944` (string)
+ DocumentType: `123` (string)
+ Notes: Received ready for processing (string)
+ InvoiceType: Contract (string)
+ BuyerOrderNo: BuyOrder1 (string)
+ BuyerSwiftAddress: SWFTBUY123 (string)
+ BuyerVatRegistrationNo: VATBUY4546 (string)
+ ClientAddress1: 1 Downer Road (string)
+ ClientAddress3: Southend (string)
+ ClientAddress4: Essex (string)
+ ClientCountryCode: GB (string)
+ ClientFiscalRegistrationNo: CLIFIS789 (string)
+ ClientPaymentTerms: 10 Days (string)
+ ClientTitle: I AM CLIENT (string)
+ ClientVatRegistrationNo: CLIVAT753 (string)
+ ClientZipCode: SS2 3FF (string)
+ DeliveryClientAddress1: 16 Del Road (string)
+ DeliveryClientAddress3: Highgate (string)
+ DeliveryClientAddress4: London (string)
+ DeliveryClientCountryCode: GB (string)
+ DeliveryClientTitle: I AM DEL CLIENT (string)
+ DeliveryClientZipCode: N16 1JJ (string)
+ DeliveryDate: `2025-07-30T00:00:00Z` (string)
+ PaymentMethod: PAYMENT (string)
+ PaymentModeDescription: TRANSFER (string)
+ SupplierAddress3: 22 Supplier Ave (string)
+ SupplierAddress4: Dudley (string)
+ SupplierCountryCode: GB (string)
+ SupplierFiscalRegistrationNo: SUPPFIS951 (string)
+ SupplierSwiftAddress: SUPSWFT357 (string)
+ SupplierTitle: I AM SUPPLIER (string)
+ SupplierZipCode: MI7 9UU (string)
+ InvoiceRecordLegs (required, array [InvoiceLeg1Create, InvoiceLeg2Create])
+ InvoiceVatRecords (required, array [InvoiceCreateVat1, InvoiceCreateVat2])

## InvoiceIdResponse (object)
+ InvoiceRecordId: 1 (number)

## InvoiceLeg1Create (object)
+ Quantity: 440.00 (required, number)
+ WeightCode: MT (required, string)
+ Value: 22000.00 (required, number)
+ Price: 50.00 (required, number)
+ VatRatePercentage: 21 (required, number)
+ InvoiceRecordLegDescription: SGR 1234 (string)
+ VatRateCode: E (string)
+ RateTypeCode: A (string)
+ PriceTypeCode: PKG (string)
+ PaymentModeCode: I (string)
+ PaymentId: Payment 1 (string)
+ BuyerOrderIdentifier: XX01 (string)
+ StartPeriod: `2025-07-14T00:00:00Z` (string)
+ EndPeriod: `2025-07-28T00:00:00Z` (string)
+ FreeFormatNote: Notes section (string)
+ BaseQuantity: 300.00 (number)
+ ValueType: Contract (string)
+ CostHeadingCode: CSP (string)
+ DocumentReference: SI2600001 (string)
+ InvoiceCurrencyCode: GBP (string)
+ PhysicalTradeId: S00001.001 (string)

## InvoiceLeg2Create (object)
+ Quantity: 200.00 (required, number)
+ WeightCode: MT (required, string)
+ Value: 12000.00 (required, number)
+ Price: 60.00 (required, number)
+ VatRatePercentage: 21 (required, number)
+ InvoiceRecordLegDescription: MLS 8523 (string)
+ VatRateCode: E (string)
+ RateTypeCode: A (string)
+ PriceTypeCode: PKG (string)
+ PaymentModeCode: I (string)
+ PaymentId: Payment 1 (string)
+ BuyerOrderIdentifier: XX01 (string)
+ StartPeriod: `2025-07-14T00:00:00Z` (string)
+ EndPeriod: `2025-07-28T00:00:00Z` (string)
+ FreeFormatNote: Notes section (string)
+ BaseQuantity: 100.00 (number)
+ ValueType: Cost (string)
+ CostHeadingCode: CSP (string)
+ DocumentReference: SI2600001 (string)
+ InvoiceCurrencyCode: GBP (string)
+ PhysicalTradeId: S00001.001 (string)

## InvoiceCreateVat1 (object)
+ ExternalVatCode: S5 (string)
+ VatPercentage: 5.00 (number)
+ VatableAmount: 500.00 (number)
+ VatAmount: 25.00 (number)
+ ItasVatCode: B (string)
+ ExemptionReasonCode: EX02 (string)
+ ExemptionReasonDescription: Exempt for internal (string)
+ InvoiceAmount: 525.00 (number)
+ VatCurrencyCode: GBP (string)

## InvoiceCreateVat2 (object)
+ ExternalVatCode: T21 (string)
+ VatPercentage: 21.00 (number)
+ VatableAmount: 400.00 (number)
+ VatAmount: 84.00 (number)
+ ItasVatCode: C (string)
+ ExemptionReasonCode: EX02 (string)
+ ExemptionReasonDescription: Exempt for internal (string)
+ InvoiceAmount: 484.00 (number)
+ VatCurrencyCode: GBP (string)

## InvoiceReadBody (object)
+ InvoiceRecordId: 1 (number)
+ AccountCode: `ABCDEFG.P` (string)
+ ClientReference: '5879101647' (string)
+ CurrencyCode: EUR (string)
+ DocumentDate: `2025-07-14T00:00:00Z` (string)
+ ValueDate: `2025-08-14T00:00:00Z` (string)
+ Name: `Coolblue N.V.` (required, string)
+ VatRegistrationNo: NL823619357Z08 (string)
+ EInvoiceId: 0478493179 (string)
+ TotalInvoiceAmount: 729.17 (number)
+ TotalInvoiceLinesExVatAmount: 745.91 (number)
+ TotalVatAmount: 16.74 (number)
+ InvoicePayableAmount: 719.27 (number)
+ IBAN: UKBMGB22 (string)
+ BIC: HBUKGB4B (string)
+ OrderNumber: Order 1 (string)
+ IsProcessed: false (boolean)
+ TaxScheme: VAT (string)
+ SchemeId: `9944` (string)
+ DocumentType: `123` (string)
+ Notes: Received ready for processing (string)
+ InvoiceType: Contract (string)
+ BuyerOrderNo: BuyOrder1 (string)
+ BuyerSwiftAddress: SWFTBUY123 (string)
+ BuyerVatRegistrationNo: VATBUY4546 (string)
+ ClientAddress1: 1 Downer Road (string)
+ ClientAddress3: Southend (string)
+ ClientAddress4: Essex (string)
+ ClientCountryCode: GB (string)
+ ClientFiscalRegistrationNo: CLIFIS789 (string)
+ ClientPaymentTerms: 10 Days (string)
+ ClientTitle: I AM CLIENT (string)
+ ClientVatRegistrationNo: CLIVAT753 (string)
+ ClientZipCode: SS2 3FF (string)
+ DeliveryClientAddress1: 16 Del Road (string)
+ DeliveryClientAddress3: Highgate (string)
+ DeliveryClientAddress4: London (string)
+ DeliveryClientCountryCode: GB (string)
+ DeliveryClientTitle: I AM DEL CLIENT (string)
+ DeliveryClientZipCode: N16 1JJ (string)
+ DeliveryDate: `2025-07-30T00:00:00Z` (string)
+ PaymentMethod: PAYMENT (string)
+ PaymentModeDescription: TRANSFER (string)
+ SupplierAddress3: 22 Supplier Ave (string)
+ SupplierAddress4: Dudley (string)
+ SupplierCountryCode: GB (string)
+ SupplierFiscalRegistrationNo: SUPPFIS951 (string)
+ SupplierSwiftAddress: SUPSWFT357 (string)
+ SupplierTitle: I AM SUPPLIER (string)
+ SupplierZipCode: MI7 9UU (string)
+ InvoiceRecordLegs (required, array [InvoiceReadLeg1, InvoiceReadLeg2])
+ InvoiceVatRecords (required, array [InvoiceReadVat1, InvoiceReadVat2])

## InvoiceUpdateBody (object)
+ InvoiceRecordId: 1 (required, number)
+ AccountCode: `ABCDEFG.P` (required, string)
+ ClientReference: '5879101647' (required, string)
+ CurrencyCode: EUR (required, string)
+ DocumentDate: `2025-07-14T00:00:00Z` (required, string)
+ ValueDate: `2025-08-14T00:00:00Z` (required, string)
+ Name: `Coolblue N.V.` (required, string)
+ VatRegistrationNo: NL823619357Z08 (required, string)
+ EInvoiceId: 0478493179 (required, string)
+ TotalInvoiceAmount: 729.17 (required, number)
+ TotalInvoiceLinesExVatAmount: 745.91 (required, number)
+ TotalVatAmount: 16.74 (required, number)
+ InvoicePayableAmount: 719.27 (required, number)
+ IBAN: UKBMGB22 (required, string)
+ BIC: HBUKGB4B (required, string)
+ OrderNumber: 'Order 1 (string)
+ TaxScheme: VAT (string)
+ SchemeId: `9944` (string)
+ DocumentType: `123` (string)
+ Notes: Process with the following note (string)
+ InvoiceType: Contract (string)
+ BuyerOrderNo: BuyOrder1 (string)
+ BuyerSwiftAddress: SWFTBUY123 (string)
+ BuyerVatRegistrationNo: VATBUY4546 (string)
+ ClientAddress1: 1 Downer Road (string)
+ ClientAddress3: Southend (string)
+ ClientAddress4: Essex (string)
+ ClientCountryCode: GB (string)
+ ClientFiscalRegistrationNo: CLIFIS789 (string)
+ ClientPaymentTerms: 10 Days (string)
+ ClientTitle: I AM CLIENT (string)
+ ClientVatRegistrationNo: CLIVAT753 (string)
+ ClientZipCode: SS2 3FF (string)
+ DeliveryClientAddress1: 16 Del Road (string)
+ DeliveryClientAddress3: Highgate (string)
+ DeliveryClientAddress4: London (string)
+ DeliveryClientCountryCode: GB (string)
+ DeliveryClientTitle: I AM DEL CLIENT (string)
+ DeliveryClientZipCode: N16 1JJ (string)
+ DeliveryDate: `2025-07-30T00:00:00Z` (string)
+ PaymentMethod: PAYMENT (string)
+ PaymentModeDescription: TRANSFER (string)
+ SupplierAddress3: 22 Supplier Ave (string)
+ SupplierAddress4: Dudley (string)
+ SupplierCountryCode: GB (string)
+ SupplierFiscalRegistrationNo: SUPPFIS951 (string)
+ SupplierSwiftAddress: SUPSWFT357 (string)
+ SupplierTitle: I AM SUPPLIER (string)
+ SupplierZipCode: MI7 9UU (string)
+ InvoiceRecordLegs (required, array [InvoiceUpdateLeg1Create, InvoiceUpdateLeg2Create])
+ InvoiceVatRecords (required, array [InvoiceReadVat1, InvoiceReadVat2])

## InvoiceReadLeg1 (object)
+ InvoiceRecordId: 1 (number)
+ InvoiceRecordLegId: 1 (number)
+ Quantity: 440.00 (number)
+ WeightCode: MT (string)
+ Value: 22000.00 (number)
+ Price: 50.00 (number)
+ VatRatePercentage: 21 (number)
+ InvoiceRecordLegDescription: SGR 1234 (string)
+ VatRateCode: E (string)
+ RateTypeCode: A (string)
+ PriceTypeCode: PKG (string)
+ PaymentModeCode: I (string)
+ PaymentId: Payment 1 (string)
+ BuyerOrderIdentifier: XX01 (string)
+ StartPeriod: `2025-07-14T00:00:00Z` (string)
+ EndPeriod: `2025-07-28T00:00:00Z` (string)
+ FreeFormatNote: Notes section (string)
+ BaseQuantity: 300.00 (number)
+ ValueType: Contract (string)
+ CostHeadingCode: CSP (string)
+ DocumentReference: SI2600001 (string)
+ InvoiceCurrencyCode: GBP (string)
+ PhysicalTradeId: S00001.001 (string)


## InvoiceReadLeg2 (object)
+ InvoiceRecordId: 1 (number)
+ InvoiceRecordLegId: 2 (number)
+ Quantity: 400.00 (number)
+ WeightCode: MT (string)
+ Value: 24000.00 (number)
+ Price: 60.00 (number)
+ VatRatePercentage: 21 (number)
+ InvoiceRecordLegDescription: MLS 8523 (string)
+ VatRateCode: E (string)
+ RateTypeCode: A (string)
+ PriceTypeCode: PKG (string)
+ PaymentModeCode: I (string)
+ PaymentId: Payment 1 (string)
+ BuyerOrderIdentifier: XX01 (string)
+ StartPeriod: `2025-07-14T00:00:00Z` (string)
+ EndPeriod: `2025-07-28T00:00:00Z` (string)
+ FreeFormatNote: Notes section (string)
+ BaseQuantity: 100.00 (number)
+ ValueType: Cost (string)
+ CostHeadingCode: CSP (string)
+ DocumentReference: SI2600001 (string)
+ InvoiceCurrencyCode: GBP (string)
+ PhysicalTradeId: S00001.001 (string)

## InvoiceReadVat1 (object)
+ InvoiceRecordId: 1 (number)
+ InvoiceVatRecordId: 1 (number)
+ ExternalVatCode: S (string)
+ VatPercentage: 5.00 (number)
+ VatableAmount: 500.00 (number)
+ VatAmount: 25.00 (number)
+ ItasVatCode: B (string)
+ ExemptionReasonCode: EX02 (string)
+ ExemptionReasonDescription: Exempt for internal (string)
+ InvoiceAmount: 525.00 (number)
+ VatCurrencyCode: GBP (string)

## InvoiceReadVat2 (object)
+ InvoiceRecordId: 1 (number)
+ InvoiceVatRecordId: 2 (number)
+ ExternalVatCode: T (string)
+ VatPercentage: 21.00 (number)
+ VatableAmount: 400.00 (number)
+ VatAmount: 84.00 (number)
+ ItasVatCode: C (string)
+ ExemptionReasonCode: EX02 (string)
+ ExemptionReasonDescription: Exempt for internal (string)
+ InvoiceAmount: 484.00 (number)
+ VatCurrencyCode: GBP (string)

## InvoiceUpdateLeg1Create (object)
+ InvoiceRecordId: 1 (required, number)
+ InvoiceRecordLegId: 1 (required, number)
+ Quantity: 440.00 (required, number)
+ WeightCode: MT (required, string)
+ Value: 22000.00 (required, number)
+ Price: 50.00 (required, number)
+ VatRatePercentage: 21 (required, number)
+ InvoiceRecordLegDescription: SGR 1234 (string)
+ VatRateCode: E (string)
+ RateTypeCode: A (string)
+ PriceTypeCode: PKG (string)
+ PaymentModeCode: I (string)
+ PaymentId: Payment 1 (string)
+ BuyerOrderIdentifier: XX01 (string)
+ StartPeriod: `2025-07-14T00:00:00Z` (string)
+ EndPeriod: `2025-07-28T00:00:00Z` (string)
+ FreeFormatNote: Notes section (string)
+ BaseQuantity: 300.00 (number)
+ ValueType: Contract (string)
+ CostHeadingCode: CSP (string)
+ DocumentReference: SI2600001 (string)
+ InvoiceCurrencyCode: GBP (string)
+ PhysicalTradeId: S00001.001 (string)

## InvoiceUpdateLeg2Create (object)
+ InvoiceRecordId: 1 (required, number)
+ InvoiceRecordLegId: 2 (required, number)
+ Quantity: 400.00 (required, number)
+ WeightCode: MT (required, string)
+ Value: 24000.00 (required, number)
+ Price: 60.00 (required, number)
+ VatRatePercentage: 21 (required, number)
+ InvoiceRecordLegDescription: MLS 8523 (string)
+ VatRateCode: E (string)
+ RateTypeCode: A (string)
+ PriceTypeCode: PKG (string)
+ PaymentModeCode: I (string)
+ PaymentId: Payment 1 (string)
+ BuyerOrderIdentifier: XX01 (string)
+ StartPeriod: `2025-07-14T00:00:00Z` (string)
+ EndPeriod: `2025-07-28T00:00:00Z` (string)
+ FreeFormatNote: Notes section (string)
+ BaseQuantity: 100.00 (number)
+ ValueType: Cost (string)
+ CostHeadingCode: CSP (string)
+ DocumentReference: SI2600001 (string)
+ InvoiceCurrencyCode: GBP (string)
+ PhysicalTradeId: S00001.001 (string)


## Pagination (object)
+ Total: 547 (number) - total number of records available
+ Top: 200 (number) - max number returned per message 
+ Skip: 400 (number) - number of records skipped
+ Returned: 146 (number) - actual number returned
